In [2]:

import numpy as np
import tensorflow as tf


tf.set_random_seed(2019)
__author__ = 'Chen Quan'


## 标量运算


In [3]:

a = tf.constant(2)
b = tf.constant(3)


In [4]:
with tf.Session() as sess:
    print("a=2, b=3")
    print("加法操作: %i" % sess.run(a + b))
    print("加法操作: %i" % sess.run(tf.add(a, b)))

    print("减法操作: %i" % sess.run(a - b))
    print("减法操作: %i" % sess.run(tf.subtract(a, b)))

    print("乘法操作: %i" % sess.run(a * b))
    print("乘法操作: %i" % sess.run(tf.multiply(a, b)))

    print("除法操作: %i" % sess.run(a / b))
    print("除法操作: %i" % sess.run(tf.divide(a, b)))


a=2, b=3


加法操作: 5
加法操作: 5
减法操作: -1
减法操作: -1
乘法操作: 6
乘法操作: 6


除法操作: 0
除法操作: 0


## 矩阵运算

In [6]:
# 使用numpy生成随机矩阵
a_numpy = np.random.randn(4, 3)
b_numpy = np.random.randn(3, 5)
c_numpy = np.random.randn(4, 3)


In [9]:
# 转为tensor
a = tf.constant(a_numpy)
b = tf.constant(b_numpy)
c = tf.constant(c_numpy)


In [15]:
with tf.Session() as sess:
    print("a", a)
    print("b", b)
    print("c", c)
    print("=================")

    print("矩阵点乘法操作:", sess.run((a @ b)))  # Since python >= 3.5 the @ operator is supported (see PEP 465).
    print("矩阵点乘法操作: ", sess.run(tf.matmul(a, b)))

    # 两个矩阵对应元素相乘
    print("矩阵叉乘法操作: ", sess.run(a * c))
    print("矩阵叉乘法操作: ", sess.run(tf.multiply(a, c)))

    # 两个矩阵对应元素相除
    print("矩阵除法操作: ", sess.run(a / c))
    print("矩阵除法操作: ", sess.run(tf.divide(a, c)))

    # 两个矩阵对应元素相加
    print("矩阵加法操作：", sess.run(a + c))
    print("矩阵加法操作：", sess.run(tf.add(a, c)))

    # 两个矩阵对应元素相减
    print("矩阵加法操作：", sess.run(a - c))
    print("矩阵加法操作：", sess.run(tf.subtract(a, c)))


a Tensor("Const_5:0", shape=(4, 3), dtype=float64)
b Tensor("Const_6:0", shape=(3, 5), dtype=float64)
c Tensor("Const_7:0", shape=(4, 3), dtype=float64)
矩阵点乘法操作: [[ 1.34700791  1.70172768 -0.68036544  0.0944788   2.35866495]
 [ 1.01005166  2.43171995  0.57547699 -0.76557106 -0.03204286]
 [ 0.56621083 -0.31803585 -0.05614873 -0.68276543 -0.01929425]
 [-0.30716183 -1.04008531 -0.7171643   0.76852734  1.04520535]]
矩阵点乘法操作:  [[ 1.34700791  1.70172768 -0.68036544  0.0944788   2.35866495]
 [ 1.01005166  2.43171995  0.57547699 -0.76557106 -0.03204286]
 [ 0.56621083 -0.31803585 -0.05614873 -0.68276543 -0.01929425]
 [-0.30716183 -1.04008531 -0.7171643   0.76852734  1.04520535]]
矩阵叉乘法操作:  [[ 0.18482089  0.79122297  0.8281558 ]
 [-0.02844849 -4.33270243  0.01406832]
 [-1.00332284  0.03843525  0.02673525]
 [ 0.06101087 -1.0284868  -0.1182547 ]]
矩阵叉乘法操作:  [[ 0.18482089  0.79122297  0.8281558 ]
 [-0.02844849 -4.33270243  0.01406832]
 [-1.00332284  0.03843525  0.02673525]
 [ 0.06101087 -1.0284868  -0

矩阵加法操作： [[-0.30852049 -0.81505445 -0.62476528]
 [-0.61463057 -4.20832019  0.34813917]
 [-2.32789516  0.02441384  0.96210366]
 [ 0.08336416  2.08354749 -0.9766663 ]]
矩阵加法操作： [[-0.30852049 -0.81505445 -0.62476528]
 [-0.61463057 -4.20832019  0.34813917]
 [-2.32789516  0.02441384  0.96210366]
 [ 0.08336416  2.08354749 -0.9766663 ]]


In [16]:
    
a_numpy = np.random.randn(4, 2)
b_numpy = np.random.randn(4, 1)
c_numpy = np.random.randn(1, 2)
a = tf.constant(a_numpy)
b = tf.constant(b_numpy)
c = tf.constant(c_numpy)

In [17]:

with tf.Session() as sess:
    print("a", a)
    print("b", b)
    print("c", c)

    # 叉乘广播 a.shape=[4,2]
    print("矩阵叉乘法操作: ", sess.run(a * b))  # b.shape=[4,1]
    print("矩阵叉乘法操作: ", sess.run(tf.multiply(a, b)))

    print("矩阵叉乘法操作: ", sess.run(a * c))  # c.shape=[1,2]
    print("矩阵叉乘法操作: ", sess.run(tf.multiply(a, c)))

    # 除法的广播
    print("矩阵除法操作: ", sess.run(a / b))
    print("矩阵除法操作: ", sess.run(tf.divide(a, b)))

    print("矩阵除法操作: ", sess.run(a / c))
    print("矩阵除法操作: ", sess.run(tf.divide(a, c)))

    # 矩阵加法的广播
    print("矩阵加法操作：", sess.run(a + b))
    print("矩阵加法操作：", sess.run(tf.add(a, b)))

    print("矩阵加法操作：", sess.run(a + c))
    print("矩阵加法操作：", sess.run(tf.add(a, c)))

    # 减法的广播
    print("矩阵加法操作：", sess.run(a - b))
    print("矩阵加法操作：", sess.run(tf.subtract(a, b)))

    print("矩阵加法操作：", sess.run(a - c))
    print("矩阵加法操作：", sess.run(tf.subtract(a, c)))


a Tensor("Const_8:0", shape=(4, 2), dtype=float64)
b Tensor("Const_9:0", shape=(4, 1), dtype=float64)
c Tensor("Const_10:0", shape=(1, 2), dtype=float64)
矩阵叉乘法操作:  [[-0.49559309  1.12944744]
 [ 0.25322846 -0.2601183 ]
 [ 0.15893883  0.37959634]
 [-0.20953453  1.75767578]]
矩阵叉乘法操作:  [[-0.49559309  1.12944744]
 [ 0.25322846 -0.2601183 ]
 [ 0.15893883  0.37959634]
 [-0.20953453  1.75767578]]
矩阵叉乘法操作:  [[ 0.33252258 -0.34654902]
 [-0.57099296  0.26822046]
 [ 0.42179006  0.46067124]
 [-0.16788504  0.64401789]]
矩阵叉乘法操作:  [[ 0.33252258 -0.34654902]
 [-0.57099296  0.26822046]
 [ 0.42179006  0.46067124]
 [-0.16788504  0.64401789]]
矩阵除法操作:  [[-0.38415322  0.87547806]
 [ 2.21685065 -2.27716672]
 [ 1.92730353  4.60301223]
 [-0.23160923  1.94284894]]
矩阵除法操作:  [[-0.38415322  0.87547806]
 [ 2.21685065 -2.27716672]
 [ 1.92730353  4.60301223]
 [-0.23160923  1.94284894]]
矩阵除法操作:  [[ 0.57254362 -2.85329461]
 [-0.98314639  2.20838014]
 [ 0.72624604  3.79291438]
 [-0.28906762  5.30249014]]
矩阵除法操作:  [[ 0.57

矩阵加法操作： [[-0.69949248 -2.13020975]
 [-1.08722376  0.43165386]
 [ 0.84063545  1.60902026]
 [ 0.73085632  2.79909627]]
矩阵加法操作： [[ 1.19841982 -0.64588246]
 [ 0.01284396  1.11813657]
 [ 1.3155549   1.6703547 ]
 [ 0.54179448  2.19644942]]
矩阵加法操作： [[ 1.19841982 -0.64588246]
 [ 0.01284396  1.11813657]
 [ 1.3155549   1.6703547 ]
 [ 0.54179448  2.19644942]]
矩阵加法操作： [[ 1.57215206  0.14143479]
 [-0.41126837  1.10760924]
 [ 0.26629429  1.0346791 ]
 [-1.17144742  0.89679253]]
矩阵加法操作： [[ 1.57215206  0.14143479]
 [-0.41126837  1.10760924]
 [ 0.26629429  1.0346791 ]
 [-1.17144742  0.89679253]]
矩阵加法操作： [[-0.32576024 -1.34289249]
 [-1.5113361   0.42112654]
 [-0.20862516  0.97334467]
 [-0.98238558  1.49943939]]
矩阵加法操作： [[-0.32576024 -1.34289249]
 [-1.5113361   0.42112654]
 [-0.20862516  0.97334467]
 [-0.98238558  1.49943939]]


## 使用占位符传输数据

In [21]:
# 创建占位符，形状为[1,]

a = tf.placeholder(tf.int8, shape=[1])  # 传入一个8位整数
b = tf.placeholder(tf.int8, shape=[1])  # 传入一个32位浮点数
c = tf.placeholder(tf.float32, shape=[1])


In [26]:
with tf.Session() as sess:
    print("a=", a, "b=", b)
    print('a={}'.format(sess.run([a], feed_dict={a: [1]})))
    print('b={}'.format(sess.run([b], feed_dict={b: [1.1]})))
    print('a*b={}'.format(sess.run([a * b], feed_dict={a: [1], b: [2]})))
    # print('a * b={}'.format(sess.run([a * b], feed_dict={b: [1.1]}))) # 报错


a= Tensor("Placeholder_3:0", shape=(1,), dtype=int8) b= Tensor("mul_15:0", shape=(1,), dtype=int8)
a=[array([1], dtype=int8)]
b=[array([1], dtype=int8)]
a*b=[array([2], dtype=int8)]
